services:
  app:
    container_name: app
    image: reivertt/tamiyochi:latest
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    depends_on:
      - mysql
    volumes:
      - data:/var/www/html
      - ./php/local.ini:/etc/php/8.2/fpm/conf.d/local.ini
    networks: 
      - laravel

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: 'cicd'
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - data:/var/www/html
    networks:
      - laravel
  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - '9000:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - data:/var/www/html
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  data: {}